# Generated by Django 6.0.7 on 2026-08-04 20:34

from django.db import migrations, models


def normalize_empty_email(apps, schema_editor):
    User = apps.get_model("authentication", "User")
    User.objects.filter(email="").update(email=None)


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_create_default_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.RunPython(
            normalize_empty_email,
            migrations.RunPython.noop,
        ),
    ]
