# Generated by Django 6.0.7 on 2026-09-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_eventlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_id', models.CharField(editable=False, help_text='Identificador corto público del error para soporte.', max_length=16, unique=True)),
                ('source', models.CharField(choices=[('server', 'Server'), ('client', 'Client')], db_index=True, default='server', max_length=16)),
                ('kind', models.CharField(blank=True, default='', max_length=200)),
                ('message', models.TextField(blank=True, default='')),
                ('path', models.CharField(blank=True, default='', max_length=500)),
                ('method', models.CharField(blank=True, default='', max_length=10)),
                ('user_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('error_id_ref', models.CharField(blank=True, default='', help_text='error_id del error en el otro lado del request (server o client).', max_length=16)),
                ('traceback', models.TextField(blank=True, default='')),
                ('client_metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source', '-created_at'], name='authenticat_source_272d03_idx'), models.Index(fields=['kind'], name='authenticat_kind_5aad4e_idx')],
            },
        ),
    ]
