# Generated by Django 6.0.7 on 2026-09-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_errorlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activated_at',
            field=models.DateTimeField(blank=True, help_text='Momento en el que el usuario activó su cuenta por email. NULL = nunca activó (puede pedir reenvío).', null=True),
        ),
    ]
