"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from pathlib import Path
from dotenv import load_dotenv
from datetime import timedelta
import dj_database_url
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")

SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
# Por defecto False: un despliegue sin la variable DEBUG emite cookies
# Secure y no filtra detalles de errores.
DEBUG = os.getenv("DEBUG", "False").lower() in ("true", "1", "yes")

# Política SameSite para las cookies de autenticación (refresh token y CSRF).
# "Lax" cubre el despliegue actual (SPA servida por Django) y el desarrollo
# con proxy. Usar "None" solo si frontend y API viven en sitios distintos;
# en ese caso las cookies se marcan Secure obligatoriamente.
AUTH_COOKIE_SAMESITE = os.getenv("AUTH_COOKIE_SAMESITE", "Lax")

if AUTH_COOKIE_SAMESITE not in ("Lax", "Strict", "None"):
    raise ImproperlyConfigured(
        "AUTH_COOKIE_SAMESITE debe ser 'Lax', 'Strict' o 'None'."
    )

ALLOWED_HOSTS = os.getenv(
    "ALLOWED_HOSTS",
    "localhost,127.0.0.1"
).split(",")

AUTH_USER_MODEL = "authentication.User"
# Application definition

SIMPLE_JWT = {
   
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),

    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),

    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    
    'AUTH_HEADER_TYPES': ('Bearer',),
}


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'authentication',
    'course',
    'teams',
    'assignments',
    'grading',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'djoser',
    "django_filters",
    "corsheaders",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'config.middleware.CspMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

FRONTEND_DIR = BASE_DIR.parent / "frontend" / "dist"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [FRONTEND_DIR],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [
    FRONTEND_DIR / "static",
]

WHITENOISE_USE_FINDERS = True

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases



DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
      "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],

"DEFAULT_THROTTLE_RATES": {
        "anon": "10/minute",
        "user": "50/minute",
        "login": "5/minute",
        "auth": "10/minute",
        "admin": "20/minute",
        "grade": "60/minute",
    },

    "DEFAULT_PAGINATION_CLASS":
        "config.pagination.DefaultPagination",

    "DEFAULT_RENDERER_CLASSES": (
        "rest_framework.renderers.JSONRenderer",
    ),
}

if DEBUG:
    REST_FRAMEWORK["DEFAULT_RENDERER_CLASSES"] = (
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    )

# The in-memory throttle cache persists across test cases (user pks repeat
# on every fresh test database), which makes large suites flaky with 429s.
if "test" in sys.argv:
    REST_FRAMEWORK["DEFAULT_THROTTLE_CLASSES"] = []
    DISABLE_THROTTLE = True

# Orígenes del frontend autorizados para CORS con credenciales. En desarrollo
# Vite corre en :5173; si el frontend se despliega en otro origen, agreguelo
# vía la variable CORS_ALLOWED_ORIGINS (separada por comas).
CORS_ALLOWED_ORIGINS = [
    o.strip()
    for o in os.getenv(
        "CORS_ALLOWED_ORIGINS",
        "http://localhost:5173,http://127.0.0.1:5173"
    ).split(",")
    if o.strip()
]

# Necesario para que el frontend pueda mantener las cookies de sesión
# (refresh token + CSRF) entre dominios durante el desarrollo.
CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in os.getenv(
        "CSRF_TRUSTED_ORIGINS",
        "http://localhost:5173,http://127.0.0.1:5173,https://uni-homework-project.onrender.com",
    ).split(",")
    if o.strip()
]

# Seguridad en producción: cookies Secure, HSTS, redirect a HTTPS.
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True

# Caché: Redis en producción (si REDIS_URL está configurado), local-mem en desarrollo.
# Para migrar a Redis: 1) pip install redis, 2) agregar REDIS_URL en Render, 3) reiniciar.
_redis_url = os.getenv("REDIS_URL")
if _redis_url:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": _redis_url,
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        }
    }

# Content-Security-Policy en modo bloqueo.
# - CSP_APPLY (default True): emite la cabecera Content-Security-Policy bloqueante.
#   Desactivar solo si algo del frontend queda fuera de la política.
# - CSP_REPORT_URI (opcional): emite ademas Content-Security-Policy-Report-Only
#   con la misma politica para seguir monitoreando violaciones sin cortar nada.
# El hash de script-src cubre el script inline del splash en frontend/index.html
# (mismo hash en fuente y en el build; recalculado si ese script cambia).
_CSP_APPLY = os.getenv("CSP_APPLY", "True").lower() in ("true", "1", "yes")
_csp_report_uri = os.getenv("CSP_REPORT_URI")

if _CSP_APPLY or _csp_report_uri:
    _CSP_POLICY = (
        "default-src 'self'; "
        "script-src 'self' "
        "'sha256-I8qldK+z9ZM3V9OY0e7rksCMQ7kY2AVpniYXb5gskFg='; "
        "style-src 'self' 'unsafe-inline'; "
        "img-src 'self' data:; "
        "font-src 'self'; "
        "connect-src 'self'; "
        "object-src 'none'; "
        "base-uri 'self'; "
        "form-action 'self'; "
        "frame-ancestors 'none'; "
    )
    if not DEBUG:
        _CSP_POLICY += "upgrade-insecure-requests; "
    if _csp_report_uri:
        _CSP_POLICY += f"report-uri {_csp_report_uri}; "

    if _CSP_APPLY:
        CSP = _CSP_POLICY
    if _csp_report_uri:
        CSP_REPORT_ONLY = _CSP_POLICY

DJOSER = {
    'SERIALIZERS': {
        'user_create': 'authentication.serializers.UserCreateSerializer',
        'current_user': 'authentication.serializers.UserSerializer',
    },
}

