# Generated by Django 6.0.7 on 2026-08-14 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.DecimalField(decimal_places=2, help_text='Score earned by the student, between 0 and the assignment max score.', max_digits=6)),
                ('is_individual', models.BooleanField(default=False, help_text='False when the score comes from the team grade; True when the teacher set a specific score for this student.')),
                ('assignment', models.ForeignKey(help_text='The assignment being graded.', on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='assignments.assignment')),
                ('graded_by', models.ForeignKey(help_text='The teacher that registered the grade.', on_delete=django.db.models.deletion.PROTECT, related_name='given_grades', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(help_text='The student receiving the grade.', on_delete=django.db.models.deletion.CASCADE, related_name='grades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['assignment', 'student'], name='grading_gra_assignm_57b0d8_idx'), models.Index(fields=['student', 'assignment'], name='grading_gra_student_4c0b39_idx')],
                'constraints': [models.UniqueConstraint(fields=('assignment', 'student'), name='unique_assignment_student_grade'), models.CheckConstraint(condition=models.Q(('score__gte', 0)), name='grades_grade_score_gte_0')],
            },
        ),
    ]
