# Generated by Django 6.0.7 on 2026-09-04 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_record', models.BooleanField(default=False, help_text='True when this change created the grade for the first time.')),
                ('old_score', models.DecimalField(blank=True, decimal_places=2, help_text='Score before the change; None on the first record.', max_digits=6, null=True)),
                ('new_score', models.DecimalField(decimal_places=2, help_text='Score after the change.', max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grade', models.ForeignKey(help_text='The grade that was changed.', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='grading.grade')),
                ('graded_by', models.ForeignKey(help_text='The teacher that registered the change.', on_delete=django.db.models.deletion.PROTECT, related_name='registered_grade_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['grade'], name='grading_gra_grade_i_90d885_idx')],
            },
        ),
    ]
