# Generated by Django 6.0.7 on 2026-09-07 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_sectionsnapshot'),
        ('grading', '0002_gradehistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalScoreSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.DecimalField(decimal_places=2, help_text='Weighted final grade (0..100) at capture time.', max_digits=5)),
                ('course', models.ForeignKey(help_text='The course the snapshot belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='final_score_snapshots', to='course.course')),
                ('student', models.ForeignKey(help_text='The student whose final grade was captured.', on_delete=django.db.models.deletion.CASCADE, related_name='final_score_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['course', 'student', 'created_at'], name='grading_fin_course__f2d9e6_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('score__gte', 0), ('score__lte', 100)), name='grading_finalscore_score_between_0_and_100')],
            },
        ),
    ]
