# Generated by Django 6.0.7 on 2026-08-01 10:57

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='course',
            name='join_code',
            field=models.CharField(default=course.models.generate_join_code, editable=False, max_length=8, unique=True),
        ),
    ]
