# Generated by Django 6.0.7 on 2026-08-03 07:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_enrollment_options_alter_course_join_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(condition=models.Q(('visibility__in', ['PRIVATE', 'PUBLIC'])), name='course_valid_visibility'),
        ),
    ]
