# Generated by Django 6.0.7 on 2026-08-21 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_enrollment_enrollment_valid_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Display name of the section, unique within the same course (e.g. '1TS1'). The same name may exist in other courses.", max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='enrollment',
            name='unique_student_course',
        ),
        migrations.AlterField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='course',
            name='visibility',
            field=models.CharField(choices=[('PRIVATE', 'Private'), ('PUBLIC', 'Public')], db_index=True, default='PRIVATE', max_length=10),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=10),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['teacher', 'is_active'], name='course_cour_teacher_93f266_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['visibility', 'is_active'], name='course_cour_visibil_7eed69_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['title'], name='course_cour_title_c8b671_idx'),
        ),
        migrations.AddField(
            model_name='section',
            name='course',
            field=models.ForeignKey(help_text='The course this section belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='course.course'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='section',
            field=models.ForeignKey(blank=True, help_text='The section of the course the student requested to join. The course is reached through Enrollment -> Section -> Course.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='course.section'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['section', 'status'], name='course_enro_section_0a44c5_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student', 'status'], name='course_enro_student_ba5c22_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['section', 'student'], name='course_enro_section_a94330_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('section', 'student'), name='unique_student_section', violation_error_message='This student already has an enrollment request for this section.'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['course', 'name'], name='course_sect_course__723919_idx'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('course', 'name'), name='course_section_unique_name_per_course', violation_error_message='A section with this name already exists in this course.'),
        ),
    ]
