# Generated by Django 6.0.7 on 2026-08-21 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_backfill_default_sections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='course',
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='section',
            field=models.ForeignKey(help_text='The section of the course the student requested to join. The course is reached through Enrollment -> Section -> Course.', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='course.section'),
        ),
    ]
