# Generated by Django 6.0.7 on 2026-09-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_backfill_course_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_id', models.IntegerField(db_index=True)),
                ('course_title', models.CharField(max_length=150)),
                ('teacher_id', models.IntegerField(db_index=True)),
                ('teacher_name', models.CharField(max_length=300)),
                ('section_id', models.IntegerField(db_index=True)),
                ('section_name', models.CharField(max_length=100)),
                ('reason', models.CharField(db_index=True, default='section_delete', max_length=32)),
                ('payload', models.JSONField(help_text='Denormalized snapshot of the section data.')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['teacher_id', 'created_at'], name='course_sect_teacher_5b1e90_idx'), models.Index(fields=['course_id'], name='course_sect_course__fe7076_idx')],
            },
        ),
    ]
