# Generated by Django 6.0.7 on 2026-09-08 21:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_sectionsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesettings',
            name='p1_acumulado_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('25.00'), help_text='Share of the final grade coming from partial 1 accumulated works. All four percentages must add up to 100.', max_digits=5),
        ),
        migrations.AddField(
            model_name='coursesettings',
            name='p1_examen_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('25.00'), help_text='Share of the final grade coming from partial 1 exams.', max_digits=5),
        ),
        migrations.AddField(
            model_name='coursesettings',
            name='p2_acumulado_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('25.00'), help_text='Share of the final grade coming from partial 2 accumulated works.', max_digits=5),
        ),
        migrations.AddField(
            model_name='coursesettings',
            name='p2_examen_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('25.00'), help_text='Share of the final grade coming from partial 2 exams.', max_digits=5),
        ),
        migrations.AddField(
            model_name='coursesettings',
            name='ponderacion_enabled',
            field=models.BooleanField(default=False, help_text='Use the per-partial grading scheme (acumulados and exams with the configured percentages) instead of the plain weighted average of every published assignment.'),
        ),
    ]
