# Generated by Django 6.0.7 on 2026-09-08 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_coursesettings_p1_acumulado_pct_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='coursesettings',
            constraint=models.CheckConstraint(condition=models.Q(('p1_acumulado_pct__gte', 0), ('p1_acumulado_pct__lte', 100), ('p1_examen_pct__gte', 0), ('p1_examen_pct__lte', 100), ('p2_acumulado_pct__gte', 0), ('p2_acumulado_pct__lte', 100), ('p2_examen_pct__gte', 0), ('p2_examen_pct__lte', 100)), name='course_coursesettings_pcts_within_0_100'),
        ),
    ]
