# Generated by Django 6.0.8 on 2026-09-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_coursesettings_percentage_bounds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesettings',
            name='ponderacion_enabled',
            field=models.BooleanField(default=False, help_text='Use the per-partial grading scheme (acumulados and exams with the configured percentages) instead of the plain average of every published assignment.'),
        ),
    ]
