# Generated by Django 6.0.7 on 2026-08-13 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0004_enrollment_enrollment_valid_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Display name of the assignment.', max_length=150)),
                ('description', models.TextField(blank=True, help_text='Optional details about the assignment.')),
                ('max_score', models.DecimalField(decimal_places=2, help_text='Maximum score of the assignment.', max_digits=6)),
                ('due_date', models.DateTimeField(blank=True, help_text='Optional deadline for the assignment.', null=True)),
                ('is_published', models.BooleanField(default=False, help_text='Drafts are hidden from students until published.')),
                ('course', models.ForeignKey(help_text='The course this assignment belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='course.course')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['course', 'is_published'], name='assignments_course__eda10d_idx'), models.Index(fields=['course', 'due_date'], name='assignments_course__2d636b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('max_score__gt', 0)), name='assignments_assignment_max_score_gt_0')],
            },
        ),
    ]
