# Generated by Django 6.0.7 on 2026-09-04 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Drafts are hidden from students until published.'),
        ),
    ]
