# Generated by Django 6.0.7 on 2026-09-04 22:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_alter_assignment_is_published'),
        ('course', '0008_backfill_course_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Relative importance of the assignment in the final weighted grade. A weight of 1 makes it count the same as the raw points.', max_digits=5),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.CheckConstraint(condition=models.Q(('weight__gt', 0)), name='assignments_assignment_weight_gt_0'),
        ),
    ]
