# Generated by Django 6.0.7 on 2026-09-08 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_assignment_weight_and_more'),
        ('course', '0010_coursesettings_p1_acumulado_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='category',
            field=models.CharField(choices=[('ACUMULADO', 'Acumulado'), ('EXAMEN', 'Examen')], default='ACUMULADO', help_text='Whether the assignment counts as accumulated work or as an exam. Exams are not weighted: their percentage is taken as-is.', max_length=10),
        ),
        migrations.AddField(
            model_name='assignment',
            name='parcial',
            field=models.CharField(choices=[('PRIMERO', 'Parcial 1'), ('SEGUNDO', 'Parcial 2')], default='PRIMERO', help_text='Which partial (term) the assignment belongs to.', max_length=10),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['course', 'category', 'parcial'], name='assignments_course__c72787_idx'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.CheckConstraint(condition=models.Q(('category__in', ['ACUMULADO', 'EXAMEN'])), name='assignments_assignment_valid_category'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.CheckConstraint(condition=models.Q(('parcial__in', ['PRIMERO', 'SEGUNDO'])), name='assignments_assignment_valid_parcial'),
        ),
    ]
