# Generated by Django 6.0.7 on 2026-09-09 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_assignment_category_assignment_parcial_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assignment',
            name='assignments_assignment_weight_gt_0',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='category',
            field=models.CharField(choices=[('ACUMULADO', 'Acumulado'), ('EXAMEN', 'Examen')], default='ACUMULADO', help_text='Whether the assignment counts as accumulated work or as an exam. Exams are weighted the same as accumulated work within a partial.', max_length=10),
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='weight',
        ),
    ]
