# Generated by Django 6.0.7 on 2026-08-04 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0004_enrollment_enrollment_valid_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Display name of the team, unique per course.', max_length=100)),
                ('course', models.ForeignKey(help_text='The course the team belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='course.course')),
                ('leader', models.ForeignKey(help_text='The student that leads the team.', on_delete=django.db.models.deletion.PROTECT, related_name='led_teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(editable=False, help_text="Denormalized copy of the team course used to enforce the 'one team per student per course' rule at the database level.", on_delete=django.db.models.deletion.CASCADE, related_name='+', to='course.course')),
                ('student', models.ForeignKey(help_text='The student that is a member of the team.', on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(help_text='The team the student belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='teams.team')),
            ],
            options={
                'ordering': ['joined_at'],
            },
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['course', 'name'], name='teams_team_course__224a48_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['course', 'leader'], name='teams_team_course__e43604_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['leader'], name='teams_team_leader__6d1ca2_idx'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('course', 'name'), name='teams_team_unique_name_per_course', violation_error_message='A team with this name already exists in this course.'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['team', 'joined_at'], name='teams_teamm_team_id_2865b4_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['student', 'team'], name='teams_teamm_student_60c077_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['course'], name='teams_teamm_course__b0f245_idx'),
        ),
        migrations.AddConstraint(
            model_name='teammember',
            constraint=models.UniqueConstraint(fields=('team', 'student'), name='teams_teammember_unique_team_student', violation_error_message='This student is already a member of the team.'),
        ),
        migrations.AddConstraint(
            model_name='teammember',
            constraint=models.UniqueConstraint(fields=('student', 'course'), name='teams_teammember_unique_student_course', violation_error_message='This student already belongs to another team in this course.'),
        ),
    ]
