# Generated by Django 6.0.7 on 2026-08-21 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_section_enrollment_section'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='team',
            name='teams_team_unique_name_per_course',
        ),
        migrations.RemoveIndex(
            model_name='team',
            name='teams_team_course__224a48_idx',
        ),
        migrations.RemoveIndex(
            model_name='team',
            name='teams_team_course__e43604_idx',
        ),
        migrations.AddField(
            model_name='team',
            name='section',
            field=models.ForeignKey(blank=True, help_text='The section the team belongs to. The course is reached through Team -> Section -> Course.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='course.section'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(help_text='Display name of the team, unique per section.', max_length=100),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='course',
            field=models.ForeignKey(editable=False, help_text="Denormalized copy of the team's section course used to enforce the 'one team per student per course' rule at the database level.", on_delete=django.db.models.deletion.CASCADE, related_name='+', to='course.course'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['section', 'name'], name='teams_team_section_6f4a63_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['section', 'leader'], name='teams_team_section_14185b_idx'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('section', 'name'), name='teams_team_unique_name_per_section', violation_error_message='A team with this name already exists in this section.'),
        ),
    ]
