# Generated by Django 6.0.7 on 2026-08-21 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_remove_enrollment_course_alter_enrollment_section'),
        ('teams', '0003_backfill_team_sections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='course',
        ),
        migrations.AlterField(
            model_name='team',
            name='section',
            field=models.ForeignKey(help_text='The section the team belongs to. The course is reached through Team -> Section -> Course.', on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='course.section'),
        ),
    ]
